name: multimodel
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python版本 (Apple Silicon支持)
  - python=3.10
  
  # 核心深度学习框架 (Apple Silicon优化)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  
  # 科学计算 (Apple Silicon优化)
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - scipy>=1.10.0
  
  # 图像处理 (Apple Silicon兼容)
  - pillow>=9.5.0
  - opencv>=4.8.0
  - scikit-image>=0.21.0
  
  # 音频处理依赖
  - ffmpeg  # 音频格式支持
  - libsndfile  # 音频文件读写
  
  # 可视化
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # 开发工具
  - jupyter>=1.0.0
  - ipywidgets>=8.0.0
  - black>=23.7.0
  - flake8>=6.0.0
  - pytest>=7.4.0
  
  # 其他工具
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - rich>=13.4.0
  - click>=8.1.0
  
  # pip依赖（conda中不可用的包）
  - pip
  - pip:
    - transformers>=4.30.0
    - librosa>=0.10.0
    - soundfile>=0.12.0
    - audioread>=3.0.0
    - nltk>=3.8
    - spacy>=3.6.0
    - jieba>=0.42.1
    - mypy>=1.5.0
